api_platform:
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    mime_types: ["multipart/form-data"]
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
  metadata_backward_compatibility_layer: false
  collection:
    pagination:
      items_per_page: 10
  exception_to_status:
    App\Exception\EmptyBodyException: 400
    App\Exception\InvalidConfirmationTokenException: 404
