security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    database:
      entity:
        class: App\Entity\User
        property: login
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    admin:
      pattern: ^/
      form_login:
        check_path: security_login
        login_path: security_login
        default_target_path: admin
        use_referer: true
      logout:
        path: security_logout

  access_control:
    - { path: ^/admin, roles: ROLE_SUPERADMIN }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
