twig:
  default_path: "%kernel.project_dir%/templates"
  form_themes: ["bootstrap_5_layout.html.twig"]
  paths:
    "%kernel.project_dir%/templates/reservations": reservations
    "%kernel.project_dir%/templates/bundles/EasyAdminBundle": admin
  globals:
    domain: "%env(DOMAIN)%"
when@test:
  twig:
    strict_variables: true
